### PR TITLE
upgrade to apollo-server 0.2.5

### PR DESCRIPTION
**Pull request by ShockiTV**

### CODE REVIEW

**Comment by ShockiTV** [comment]
agreed

**Comment by chrisslater** [comment]
It was really useful seeing this PR to understand Apollo server. Is there any reason why this isn't a part of master?

**Comment by helfer** [comment]
It's a bit unfortunate, but the tutorial (post + video) tells people to clone this repo, and it uses the master branch, so if we updated the master branch, a lot of people would get stuck.

**Comment by helfer** [comment]
I'm going to add a note here and in the video explaining that apollo-server is now version 0.2 and what that means.

**Comment by helfer** [comment]
See #19

**Pull request closed without merging**
